
enum PERSON_ON_BOARD_TYPES {
    CREW,
    PAX
}

enum ORGANIZATION_TYPES {
    AUTHORITY,
    RSO,
    AGENT_COMPANY
}

enum LOCATION_SOURCES {
    IMO_INTERNAL,
    IMO_EXTERNAL
}

enum SHIP_STATUSES {
    TO_BE_PROCESSED,
    INACTIVE,
    ACTIVE
}
export { PERSON_ON_BOARD_TYPES, ORGANIZATION_TYPES, LOCATION_SOURCES, SHIP_STATUSES };
