const PASSWORD_COMPONENT_NAME = {
    SET: 'SET',
    RESET: 'RESET',
    CHANGE: 'CHANGE'
};

enum PASSWORD_COMPONENT_TYPE {
    SET,
    RESET,
    CHANGE
}

export { PASSWORD_COMPONENT_NAME, PASSWORD_COMPONENT_TYPE };
