version: '3.8'

services:
  backend.devcontainer:
    build: ./Server
    ports:
      - 5000:5000
    volumes:
      - ./Server:/workspaces/backend
    environment:
      AppSettings__Secret: SuperSeADasd1235t4asdcret
      ASPNETCORE_URLS: http://backend.devcontainer:5000
    depends_on:
      db:
        condition: service_healthy
    restart: always
    

  db:
    image: postgres:10-alpine
    restart: unless-stopped
    ports:
      - 5431:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
         - ./Server/SqlScripts/Create_and_populate_DB.sql:/docker-entrypoint-initdb.d/Create_and_populate_DB.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 10s

  frontend.devcontainer:
    build: ./Client
    ports:
      - 4200:4200
    depends_on:
      - backend.devcontainer
    develop:
      watch:
        - path: ./Client/package.json
          action: rebuild
        - path: ./Client/package-lock.json
          action: rebuild 
        - path: ./Client
          target: /app
          ignore:
            - node_modules/
          action: sync
