name: Apply On Push Infrastructure Terraform

on:
  push:
    branches: 
      - deploy-infra-terraformv6
    paths:
      - 'terraform/**'
     
permissions:
  id-token: write
  contents: read
  
jobs:
    terraform:
      name: 'Terraform'
      runs-on: ubuntu-latest
      environment: dev-preview
      env:
        ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
        ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
        ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
        ARM_USE_OIDC: "true"

      defaults:
        run:
          shell: bash
          working-directory: ./terraform
  
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: 1.x
        
        - name: 'Az CLI login using OIDC'
          uses: azure/login@v2
          with:
            client-id: ${{ vars.ARM_CLIENT_ID }}
            tenant-id: ${{ vars.ARM_TENANT_ID }}
            subscription-id: ${{ vars.ARM_SUBSCRIPTION_ID }}
  
        - name: Terraform init
          id: init
          run: |
            set -a 
            source ../.env.backend
            terraform init \
              -backend-config="resource_group_name=$TF_VAR_state_resource_group_name" \
              -backend-config="storage_account_name=$TF_VAR_state_storage_account_name"
  
        - name: Terraform validate
          id: validate
          run: terraform validate -no-color
  
        - name: Terraform plan
          id: plan
          run: terraform plan -no-color
        
        # - name: Terraform apply backend
        #   id: apply-backend
        #   run: terraform apply -target=azurerm_container_app.backend -auto-approve
        - name: Terraform apply
          id: apply
          run: terraform apply -auto-approve
  