name: Apply On Push Infrastructure Terraform

on:
  push:
    branches: 
      - master
    paths:
      - 'terraform/**'
      - '.github/workflows/**'

  pull_request:
    branches:
      - master
    types:
      - closed
    paths:
      - 'terraform/**'
      - '.github/workflows/**'

  workflow_dispatch:
    inputs:
      workspace:
        description: Choose the terraform workspace
        type: choice
        required: true
        options:
          - dev-preview
          - dev
          - prod


permissions:
  id-token: write
  contents: read
  
jobs:
    terraform:
      if: github.event.pull_request.merged == true || github.event_name == 'push'
      name: 'Terraform'
      runs-on: ubuntu-latest
      environment: dev-preview
      env:
        ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
        ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
        ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
        ARM_USE_OIDC: "true"

      defaults:
        run:
          shell: bash
          working-directory: ./terraform
  
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: 1.x
        
        - name: Az CLI login using OIDC
          uses: azure/login@v2
          with:
            client-id: ${{ vars.ARM_CLIENT_ID }}
            tenant-id: ${{ vars.ARM_TENANT_ID }}
            subscription-id: ${{ vars.ARM_SUBSCRIPTION_ID }}
        
        - name: Terraform init
          id: init
          run: |
            set -a 
            source ../.env.backend
            terraform init -upgrade \
              -backend-config="resource_group_name=$TF_VAR_state_resource_group_name" \
              -backend-config="storage_account_name=$TF_VAR_state_storage_account_name"
        
        - name: Select or create workspace
          id: select-or-create
          run: terraform workspace select -or-create ${{ github.event.inputs.workspace || 'dev-preview' }}
      
        - name: Terraform apply
          id: apply
          run: terraform apply -auto-approve
  