name: Docker Build, Push, and Deploy

on:
  push:
    branches: 
      - deploy-infra-terraformv6
    paths-ignore:
      - 'terraform/**'
      - 'workflows/**'

permissions:
  id-token: write
  contents: read

jobs:
  docker:
    name: 'Docker Build and Push'
    runs-on: ubuntu-latest
    environment: dev-preview
    env:
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
      ARM_USE_OIDC: "true"

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: 'Az CLI login using OIDC'
        uses: azure/login@v2
        with:
          client-id: ${{ vars.ARM_CLIENT_ID }}
          tenant-id: ${{ vars.ARM_TENANT_ID }}
          subscription-id: ${{ vars.ARM_SUBSCRIPTION_ID }}

      - name: Log in to ACR
        run: az acr login --name crimomswdev

      - name: Build and push Client Docker image
        run: |
          pwd && docker buildx build --push --tag crimomswdev.azurecr.io/client:${{ github.sha }} ../IMOMaritimeSingleWindow/Client
      - name: Build and push Server Docker image
        run: |
          pwd && docker buildx build --push --tag crimomswdev.azurecr.io/server:${{ github.sha }} ../IMOMaritimeSingleWindow/Server

  container_apps:
    name: 'Deploy Images to Container Apps'
    needs: docker  
    runs-on: ubuntu-latest
    environment: dev-preview
    env:
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
      ARM_USE_OIDC: "true"

    steps:
      - name: 'Az CLI login using OIDC'
        uses: azure/login@v2
        with:
          client-id: ${{ vars.ARM_CLIENT_ID }}
          tenant-id: ${{ vars.ARM_TENANT_ID }}
          subscription-id: ${{ vars.ARM_SUBSCRIPTION_ID }}

      - name: Deploy Backend Container App
        uses: azure/container-apps-deploy-action@v1
        with:
            acrName: crimomswdev
            containerAppName: backend-imomsw-dev-preview
            resourceGroup: rg-imo-msw-terraform-dev-preview
            imageToDeploy: crimomswdev.azurecr.io/server:${{ github.sha }}

      - name: Deploy Frontend Container App
        uses: azure/container-apps-deploy-action@v1
        with:
            acrName: crimomswdev
            containerAppName: frontend-imomsw-dev-preview
            resourceGroup: rg-imo-msw-terraform-dev-preview
            imageToDeploy: crimomswdev.azurecr.io/client:${{ github.sha }}
