name: Build Container Apps 

on:
  workflow_run:
    workflows:
      - DockerBuildandPush
    types:
      - completed
    branches:
      - deploy-infra-terraformv6

permissions:
  id-token: write
  contents: read

jobs:
  container_apps:
    name: 'Deploy Images to Container Apps'
    runs-on: ubuntu-latest
    environment: dev-preview
    env:
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
      ARM_USE_OIDC: "true"

    steps:
      - name: 'Az CLI login using OIDC'
        uses: azure/login@v2
        with:
          client-id: ${{ vars.ARM_CLIENT_ID }}
          tenant-id: ${{ vars.ARM_TENANT_ID }}
          subscription-id: ${{ vars.ARM_SUBSCRIPTION_ID }}

      - name: Deploy Backend Container App
        uses: azure/container-apps-deploy-action@v1
        with:
            acrName: crimomsw
            containerAppName: backend-imomsw-dev-preview
            resourceGroup: rg-imo-msw-terraform-dev-preview
            imageToDeploy: crimomsw.azurecr.io/server:${{ github.sha }}

      - name: Deploy Frontend Container App
        uses: azure/container-apps-deploy-action@v1
        with:
            acrName: crimomsw
            containerAppName: frontend-imomsw-dev-preview
            resourceGroup: rg-imo-msw-terraform-dev-preview
            imageToDeploy: crimomsw.azurecr.io/client:${{ github.sha }}